### ISSUE TITLE
Release roadmap

### ISSUE THREAD

**Issue by mythmakerseven** [mythmakerseven/chromapoll#16]
Once all of these things are finished, I will release Chromapoll and heavily wind down development.

- [x] slide-in burger menu to replace navbar links on mobile
- [x] nice animations (see https://github.com/mythmakerseven/chromapoll/issues/17)
- [x] line up chromas properly in the `LatestPolls` list
- [x] a little more explanation of what Chromapoll is on the homepage
- [x] web socket for updating polls without a browser refresh
- [x] display errors from server response for voting and poll creation
- [x] remember polls the user has already voted in and don't use visual effects that imply interactivity on the choices for those polls
- [x] validation on both client and server to make sure provided colors are valid hex codes
- [x] change to dark text on a choice if the color is too bright
- [x] fix https://github.com/mythmakerseven/chromapoll/issues/11

Last thing to do immediately before release:

- [x] enable the IP-checking code (already written, just commented out for ease of development)

**Comment by mythmakerseven** [comment]
MISSION ACCOMPLISHED
