### ISSUE TITLE
Animations roadmap

### ISSUE THREAD

**Issue by mythmakerseven** [mythmakerseven/chromapoll#17]
Animations will be added in the following places:

- [x] adding/removing a choice item in the `CreatePoll` form
- [x] simple intro animation on the homepage
- [x] slide-in for the burger menu
- [x] trail animation for the polls in the `LatestPolls` component
- [x] subtle bounce effect on Chroma/Pie circle when a new vote comes in

**Comment by mythmakerseven** [comment]
Done!
